ALTER TABLE "company" ALTER COLUMN "description" SET DEFAULT '';

ALTER TABLE "project" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "resource" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;