ALTER TABLE IF EXISTS "resource_environment"
    ADD COLUMN IF NOT EXISTS "databasename" VARCHAR NOT NULL;

ALTER TABLE IF EXISTS "resource_environment"
    DROP COLUMN IF EXISTS "vault_path" ,
    DROP COLUMN IF EXISTS "project_id",
    DROP COLUMN IF EXISTS "service_type" ,
    DROP COLUMN IF EXISTS "resource_type",
    DROP COLUMN IF EXISTS "host",
    DROP COLUMN IF EXISTS "port",
    DROP COLUMN IF EXISTS "username",
    DROP COLUMN IF EXISTS "database";

ALTER TABLE IF EXISTS "resource"
    ADD COLUMN IF NOT EXISTS "vault_path" VARCHAR NOT NULL,
    ADD COLUMN IF NOT EXISTS "service_type" SMALLINT NOT NULL,
    ADD COLUMN IF NOT EXISTS "resource_type" SMALLINT NOT NULL,
    ADD COLUMN IF NOT EXISTS "host" VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS "port" INTEGER NOT NULL,
    ADD COLUMN IF NOT EXISTS "username" VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS "database" VARCHAR(255) NOT NULL;