ALTER TABLE resource ADD COLUMN IF NOT EXISTS "host" VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "port" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "username" VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "database" VARCHAR(255) NOT NULL DEFAULT '';