CREATE TABLE IF NOT EXISTS project_configs (
    "id" UUID PRIMARY KEY,
    "project_id" UUID REFERENCES "project"("id") NOT NULL UNIQUE,
    "CONVERT_TEMPLATE_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "CONVERT_TEMPLATE_SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "HTTP_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "HTTP_SCHEME" VARCHAR NOT NULL DEFAULT '' ,
    "SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "ANALYTICS_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "ANALYTICS_SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "API_REF_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "API_REF_SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "CHAT_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "CHAT_SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "FUNCTION_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "FUNCTION_SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "NOTIFICATION_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "NOTIFICATION_SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "OBJECT_BUILDER_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "OBJECT_BUILDER_HIGH_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "OBJECT_BUILDER_LOW_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "OBJECT_BUILDER_SERVICE_HIGHT_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "OBJECT_BUILDER_SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "OBJECT_BUILDER_SERVICE_LOW_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "QUERY_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "QUERY_SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "SCENARIO_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "SCENARIO_HTTP_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "SCENARIO_SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "SMS_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "SMS_SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "TEMPLATE_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "TEMPLATE_SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "VERSIONING_GRPC_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "VERSIONING_SERVICE_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "MONGO_HOST" VARCHAR NOT NULL DEFAULT '' ,
    "MONGO_PORT" VARCHAR NOT NULL DEFAULT '' ,
    "others" jsonb DEFAULT '{}', 
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DO
$$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_type
        WHERE typname = 'node_type_enum'
    ) THEN
        ALTER TYPE node_type_enum ADD VALUE IF NOT EXISTS 'ENTER_PRICE';
    END IF;
END;
$$;