ALTER TABLE IF EXISTS "project_configs"
    ADD COLUMN IF NOT EXISTS "COMPANY_SERVICE_MONGO_USER" VARCHAR NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS "project_configs"
    ADD COLUMN IF NOT EXISTS "COMPANY_SERVICE_MONGO_PASSWORD" VARCHAR NOT NULL DEFAULT '';