ALTER TABLE "project_configs" DROP COLUMN IF EXISTS "REDIS_HOST";

ALTER TABLE "project_configs" DROP COLUMN IF EXISTS "REDIS_PORT";

ALTER TABLE "project_configs" DROP COLUMN IF EXISTS "REDIS_DATABASE";

ALTER TABLE "project_configs" DROP COLUMN IF EXISTS "REDIS_PASSWORD";