ALTER TABLE IF EXISTS "project_configs"
    ADD COLUMN IF NOT EXISTS "REDIS_HOST" VARCHAR NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS "project_configs"
    ADD COLUMN IF NOT EXISTS "REDIS_PORT" VARCHAR NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS "project_configs"
    ADD COLUMN IF NOT EXISTS "REDIS_DATABASE" VARCHAR NOT NULL DEFAULT '0';

ALTER TABLE IF EXISTS "project_configs"
    ADD COLUMN IF NOT EXISTS "REDIS_PASSWORD" VARCHAR NOT NULL DEFAULT '';