-- Seeded four metered items and their per-tier limits.
--
-- The hosted product's price list used to be seeded here. The open-source
-- build has no billing: the service code that read these tables was removed,
-- so the tables ship empty and the rows would only be commercial data with
-- nothing to read them. The schema itself stays, so a fork that wants billing
-- has somewhere to put it.
