-- Once created ugen_billing_period and its subscription columns.
--
-- Removed with the Ugen surface: the app generator is not part of the
-- open-source build, and nothing here was read by anything that remains.
